name: Run OPA Tests  
on: 
  # Run tests on each commit, newly opened/reopened PR, and
  # PR review submission (e.g. approval)
  push:
    paths:
      - "**.rego"
  pull_request:
    types: [opened, reopened]
    branches:
      - "main"
    paths:
      - "**.rego"
  pull_request_review:
    types: [submitted]
    branches:
      - "main"

jobs:
  Run-OPA-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v1
      with:
        version: latest

    - name: Run OPA Tests 
      run: opa test Rego/*.rego Testing/**/*.rego -v
